# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=30)),
                ('company_description', models.CharField(max_length=200)),
                ('docfile', models.FileField(upload_to=b'documents/company/%Y/%m/%d')),
                ('company_adress_of_location', models.CharField(max_length=100)),
                ('company_numero', models.CharField(max_length=10)),
                ('company_block', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite_Company',
            fields=[
                ('favorite_company_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite_Product',
            fields=[
                ('favorite_product_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite_Service',
            fields=[
                ('favorite_service_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('docfile', models.FileField(upload_to=b'documents/product/%Y/%m/%d')),
                ('adress_of_location', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('localizacao_block', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=30)),
                ('service_description', models.CharField(max_length=200)),
                ('docfile', models.FileField(upload_to=b'documents/service/%Y/%m/%d')),
                ('service_adress_of_location', models.CharField(max_length=100)),
                ('service_numero', models.CharField(max_length=10)),
                ('service_block', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=80)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User'),
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User'),
        ),
        migrations.AddField(
            model_name='favorite_service',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User'),
        ),
        migrations.AddField(
            model_name='favorite_product',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User'),
        ),
        migrations.AddField(
            model_name='favorite_company',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User'),
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User'),
        ),
    ]
